version: '2.3'
services:
  rtmp:
    image: yukimochi/vrc_rtmp:latest
    restart: always
    ports:
      - "80:80"
      - "1935:1935"
    mem_limit: 1024M
    volumes:
      - "./static:/static"
      - "./logs:/var/log/nginx"
      - "./nginx.conf:/etc/nginx/nginx.conf"

  # Streamkey authentication.
  auth:
    image: yukimochi/vrc_rtmp:auth
    restart: always
    mem_limit: 64M
    volumes:
      - "./auth.json:/auth/auth.json"
